version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
       image: docker.elastic.co/kibana/kibana:8.8.0
       ports:
        - 5601:5601
       container_name: kibana
       environment:
          - "ELASTICSEARCH_URL=http://localhost:9200"
       depends_on:
          - elasticsearch